import './globals.css';
import type { Metadata } from 'next';
import { josefinSans } from '../../public/fonts';
import Header from '@/components/Layouts/Header';
import Footer from '@/components/Layouts/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={josefinSans.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
