name: SimplePipeline

on: 
  push:
    branches: [main]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 15
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
        
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies  
        run: pnpm install

      - name: Lint
        run: pnpm lint

        env:
          CI: true
